[2023-08-30T20:00:02.323+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_migration.data_migration manual__2023-08-30T20:00:01.152599+00:00 [queued]>
[2023-08-30T20:00:02.331+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_migration.data_migration manual__2023-08-30T20:00:01.152599+00:00 [queued]>
[2023-08-30T20:00:02.332+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-30T20:00:02.347+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_migration> on 2023-08-30 20:00:01.152599+00:00
[2023-08-30T20:00:02.353+0000] {standard_task_runner.py:57} INFO - Started process 214 to run task
[2023-08-30T20:00:02.356+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_migration', 'data_migration', 'manual__2023-08-30T20:00:01.152599+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_mig_dag.py', '--cfg-path', '/tmp/tmp9pld4t3_']
[2023-08-30T20:00:02.366+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask data_migration
[2023-08-30T20:00:02.386+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T20:00:02.432+0000] {task_command.py:415} INFO - Running <TaskInstance: data_migration.data_migration manual__2023-08-30T20:00:01.152599+00:00 [running]> on host 3938d7abd9ff
[2023-08-30T20:00:02.512+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_migration' AIRFLOW_CTX_TASK_ID='data_migration' AIRFLOW_CTX_EXECUTION_DATE='2023-08-30T20:00:01.152599+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-30T20:00:01.152599+00:00'
[2023-08-30T20:00:02.515+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-30T20:00:02.517+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/data_migration.py --connection postgresql+psycopg2://***:***@postgres/***']
[2023-08-30T20:00:02.529+0000] {subprocess.py:86} INFO - Output:
[2023-08-30T20:00:02.946+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-08-30T20:00:02.948+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/data_migration.py", line 4, in <module>
[2023-08-30T20:00:02.949+0000] {subprocess.py:93} INFO -     from model import Connection
[2023-08-30T20:00:02.951+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/model.py", line 5, in <module>
[2023-08-30T20:00:02.952+0000] {subprocess.py:93} INFO -     from geoalchemy2 import Geometry
[2023-08-30T20:00:02.954+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'geoalchemy2'
[2023-08-30T20:00:02.980+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-30T20:00:02.992+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-30T20:00:02.996+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=data_migration, task_id=data_migration, execution_date=20230830T200001, start_date=20230830T200002, end_date=20230830T200002
[2023-08-30T20:00:03.009+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task data_migration (Bash command failed. The command returned a non-zero exit code 1.; 214)
[2023-08-30T20:00:03.025+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-30T20:00:03.040+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
