[2023-08-30T19:07:08.470+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: traffic_report.import_data_to_csv manual__2023-08-30T19:04:58.577937+00:00 [queued]>
[2023-08-30T19:07:08.477+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: traffic_report.import_data_to_csv manual__2023-08-30T19:04:58.577937+00:00 [queued]>
[2023-08-30T19:07:08.478+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-08-30T19:07:08.486+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): import_data_to_csv> on 2023-08-30 19:04:58.577937+00:00
[2023-08-30T19:07:08.491+0000] {standard_task_runner.py:57} INFO - Started process 265 to run task
[2023-08-30T19:07:08.493+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'traffic_report', 'import_data_to_csv', 'manual__2023-08-30T19:04:58.577937+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/traffic_dag.py', '--cfg-path', '/tmp/tmpegilen35']
[2023-08-30T19:07:08.496+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask import_data_to_csv
[2023-08-30T19:07:08.510+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T19:07:08.541+0000] {task_command.py:415} INFO - Running <TaskInstance: traffic_report.import_data_to_csv manual__2023-08-30T19:04:58.577937+00:00 [running]> on host d8e92578c4cc
[2023-08-30T19:07:08.597+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='traffic_report' AIRFLOW_CTX_TASK_ID='import_data_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2023-08-30T19:04:58.577937+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-30T19:04:58.577937+00:00'
[2023-08-30T19:07:08.599+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-30T19:07:08.600+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python ./dags/data_ingestion.py --date 2023-08-30']
[2023-08-30T19:07:08.607+0000] {subprocess.py:86} INFO - Output:
[2023-08-30T19:07:08.666+0000] {subprocess.py:93} INFO - python: can't open file './dags/data_ingestion.py': [Errno 2] No such file or directory
[2023-08-30T19:07:08.669+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-08-30T19:07:08.680+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-08-30T19:07:08.684+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=traffic_report, task_id=import_data_to_csv, execution_date=20230830T190458, start_date=20230830T190708, end_date=20230830T190708
[2023-08-30T19:07:08.693+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 24 for task import_data_to_csv (Bash command failed. The command returned a non-zero exit code 2.; 265)
[2023-08-30T19:07:08.705+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-30T19:07:08.722+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
