[2023-08-29T22:21:58.358+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: traffic_report.import_data_to_csv manual__2023-08-29T22:21:56.861001+00:00 [queued]>
[2023-08-29T22:21:58.364+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: traffic_report.import_data_to_csv manual__2023-08-29T22:21:56.861001+00:00 [queued]>
[2023-08-29T22:21:58.365+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-29T22:21:58.374+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): import_data_to_csv> on 2023-08-29 22:21:56.861001+00:00
[2023-08-29T22:21:58.379+0000] {standard_task_runner.py:57} INFO - Started process 6858 to run task
[2023-08-29T22:21:58.382+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'traffic_report', 'import_data_to_csv', 'manual__2023-08-29T22:21:56.861001+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/traffic_dag.py', '--cfg-path', '/tmp/tmp1w2_g6sb']
[2023-08-29T22:21:58.387+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask import_data_to_csv
[2023-08-29T22:21:58.405+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-29T22:21:58.439+0000] {task_command.py:415} INFO - Running <TaskInstance: traffic_report.import_data_to_csv manual__2023-08-29T22:21:56.861001+00:00 [running]> on host e69093e17de8
[2023-08-29T22:21:58.495+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='traffic_report' AIRFLOW_CTX_TASK_ID='import_data_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T22:21:56.861001+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-29T22:21:56.861001+00:00'
[2023-08-29T22:21:58.497+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-29T22:21:58.499+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /Users/jinee.hira/Dropbox/virtual_envs/austin-flow/***/dags/data_ingestion.py --date 2023-08-29']
[2023-08-29T22:21:58.512+0000] {subprocess.py:86} INFO - Output:
[2023-08-29T22:21:58.570+0000] {subprocess.py:93} INFO - python: can't open file '/Users/jinee.hira/Dropbox/virtual_envs/austin-flow/***/dags/data_ingestion.py': [Errno 2] No such file or directory
[2023-08-29T22:21:58.574+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-08-29T22:21:58.586+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-08-29T22:21:58.589+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=traffic_report, task_id=import_data_to_csv, execution_date=20230829T222156, start_date=20230829T222158, end_date=20230829T222158
[2023-08-29T22:21:58.601+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 38 for task import_data_to_csv (Bash command failed. The command returned a non-zero exit code 2.; 6858)
[2023-08-29T22:21:58.635+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-29T22:21:58.655+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
