[2023-08-29T20:30:13.546+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: traffic_report.import_data_to_csv manual__2023-08-29T20:30:12.038390+00:00 [queued]>
[2023-08-29T20:30:13.553+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: traffic_report.import_data_to_csv manual__2023-08-29T20:30:12.038390+00:00 [queued]>
[2023-08-29T20:30:13.554+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-29T20:30:13.562+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): import_data_to_csv> on 2023-08-29 20:30:12.038390+00:00
[2023-08-29T20:30:13.567+0000] {standard_task_runner.py:57} INFO - Started process 2251 to run task
[2023-08-29T20:30:13.570+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'traffic_report', 'import_data_to_csv', 'manual__2023-08-29T20:30:12.038390+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/traffic_dag.py', '--cfg-path', '/tmp/tmp4bd98wkf']
[2023-08-29T20:30:13.573+0000] {standard_task_runner.py:85} INFO - Job 34: Subtask import_data_to_csv
[2023-08-29T20:30:13.588+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-29T20:30:13.623+0000] {task_command.py:415} INFO - Running <TaskInstance: traffic_report.import_data_to_csv manual__2023-08-29T20:30:12.038390+00:00 [running]> on host e69093e17de8
[2023-08-29T20:30:13.685+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='traffic_report' AIRFLOW_CTX_TASK_ID='import_data_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T20:30:12.038390+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-29T20:30:12.038390+00:00'
[2023-08-29T20:30:13.690+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-29T20:30:13.691+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /Users/jinee.hira/Dropbox/virtual_envs/austin-flow/***/dags/data_ingestion.py --date 2023-08-29']
[2023-08-29T20:30:13.700+0000] {subprocess.py:86} INFO - Output:
[2023-08-29T20:30:13.763+0000] {subprocess.py:93} INFO - python: can't open file '/Users/jinee.hira/Dropbox/virtual_envs/austin-flow/***/dags/data_ingestion.py': [Errno 2] No such file or directory
[2023-08-29T20:30:13.766+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-08-29T20:30:13.777+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-08-29T20:30:13.782+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=traffic_report, task_id=import_data_to_csv, execution_date=20230829T203012, start_date=20230829T203013, end_date=20230829T203013
[2023-08-29T20:30:13.791+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 34 for task import_data_to_csv (Bash command failed. The command returned a non-zero exit code 2.; 2251)
[2023-08-29T20:30:13.829+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-29T20:30:13.845+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
